spring:
  profiles:
    active:
      @spring.profiles.active@
  datasource:
    url: @datasource.url@
    username: @datasource.username@
    password: @datasource.password@
    driver-class-name: @datasource.driver-class-name@
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
#    uncomment to init and populate the database
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
#    initialization-mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            #noncontextual lob creation switch-on
            #https://github.com/spring-projects/spring-boot/issues/12007#issuecomment-369388646
            non_contextual_creation: true
        format_sql: true
        ddl-auto: validate
        dialect: @jpa.properties.hibernate.dialect@
    show-sql: true